### ISSUE TITLE
Windows

### ISSUE THREAD

**Issue by wuast94** [linuxserver/docker-netbootxyz#10]
Is it Possible to Boot/Install Windows with this docker container ? :) I'm a bit confused here so sry for the question

**Comment by thelamer** [comment]
I would recommend discord as a platform for support in doing this. 
I know driz in the lsio discord https://discord.gg/YWrKVTn and netboot discord https://discord.gg/An6PA2a has this setup along with PEs he created. 
There is a history of setting up the windows assets in the containers webserver in #general of netboot discord, I think it also involves Samba. The short summary is you put the assets in a folder and then you set the `win_base_url` variable in the boot.cfg .
