### ISSUE TITLE
preseed does not work

### ISSUE THREAD

**Issue by nickkostov** [linuxserver/docker-netbootxyz#25]
I used to install Ubuntu 20.04 using the preseed option but for some reason it is not working now. What happens is that it seems to skip and it downloads ubuntu server?

**Comment by j0nnymoe** [comment]
You've ignored the issue template when opening this issue. Please make sure you provide the information requested.

**Comment by nickkostov** [comment]
I understand, I opened it from my phone I will fix that right away!
