### ISSUE TITLE
centos mirrors need update

### ISSUE THREAD

**Issue by wbx-github** [linuxserver/docker-netbootxyz#29]
Hi,

the URL's for the centos mirrors are not working anymore. Can you please Update CentOS 7/8 menu entries.

thanks in advance
 Waldemar

**Comment by j0nnymoe** [comment]
You need to report this upstream to netboot directly.

**Comment by tobbenb** [comment]
That is something you have to ask the netboot devs about. We just package it into a container.

**Comment by wbx-github** [comment]
Do you have any URL or hint where to report this bug? Where is the upstream for netboot located?

**Comment by tobbenb** [comment]
You could click on the netboot link in the readme to get to theor website.
