### ISSUE TITLE
OpenWrt Settings doenst seem to work

### ISSUE THREAD

**Issue by SquallHalle** [linuxserver/docker-netbootxyz#36]
Using OpenWrt  21.02.0 
## Expected Behavior
 
`uci set dhcp.@dnsmasq[0].dhcp_match=set:bios,60,PXEClient:Arch:00000
uci set dhcp.@dnsmasq[0].dhcp_boot=tag:bios,netboot.xyz.kpxe,,YOURSERVERIP
uci set dhcp.@dnsmasq[0].dhcp_match=set:efi32,60,PXEClient:Arch:00002
uci set dhcp.@dnsmasq[0].dhcp_boot=tag:efi32,netboot.xyz.efi,,YOURSERVERIP
uci set dhcp.@dnsmasq[0].dhcp_match=set:efi32-1,60,PXEClient:Arch:00006
uci set dhcp.@dnsmasq[0].dhcp_boot=tag:efi32-1,netboot.xyz.efi,,YOURSERVERIP
uci set dhcp.@dnsmasq[0].dhcp_match=set:efi64,60,PXEClient:Arch:00007
uci set dhcp.@dnsmasq[0].dhcp_boot=tag:efi64,netboot.xyz.efi,,YOURSERVERIP
uci set dhcp.@dnsmasq[0].dhcp_match=set:efi64-1,60,PXEClient:Arch:00008
uci set dhcp.@dnsmasq[0].dhcp_boot=tag:efi64-1,netboot.xyz.efi,,YOURSERVERIP
uci set dhcp.@dnsmasq[0].dhcp_match=set:efi64-2,60,PXEClient:Arch:00009
uci set dhcp.@dnsmasq[0].dhcp_boot=tag:efi64-2,netboot.xyz.efi,,YOURSERVERIP
uci commit
/etc/init.d/dnsmasq restart`

using this and get efi for efi maschiens and kpxe for older maschines

## Current Behavior
doenst work, it always uses the last entrie and you find only the last one in /etc/config/dhcp

## Solution
thanks to AreYouLoco in this Thread: https://forum.turris.cz/t/add-multiple-dhcp-match-and-dhcp-boot-combinations/12318
if you the following to /etc/dnsmasq.conf it works:

`dhcp-match=set:bios,60,PXEClient:Arch:00000
dhcp-boot=tag:bios,netboot.xyz.kpxe,,YOURSERVERIP
dhcp-match=set:efi32,60,PXEClient:Arch:00002
dhcp-boot=tag:efi32,netboot.xyz.efi,,YOURSERVERIP
dhcp-match=set:efi32-1,60,PXEClient:Arch:00006
dhcp-boot=tag:efi32-1,netboot.xyz.efi,,YOURSERVERIP
dhcp-match=set:efi64,60,PXEClient:Arch:00007
dhcp-boot=tag:efi64,netboot.xyz.efi,,YOURSERVERIP
dhcp-match=set:efi64-1,60,PXEClient:Arch:00008
dhcp-boot=tag:efi64-1,netboot.xyz.efi,,YOURSERVERIP
dhcp-match=set:efi64-2,60,PXEClient:Arch:00009`

**Comment by aphorise** [comment]
Why has this been closed with any resolution?

**Comment by aptalca** [comment]
It's not closed

**Comment by aphorise** [comment]
My bad sorry - anything I can do?

**Comment by drizuid** [comment]
how to setup your dhcp server is not in scope for our container. I suggest reviewing your dhcp server daemon's documentation and/or seeking guidance from the netbootxyz devs. We support the container, not the application within the container.. so the dhcp server that isn't related to either, is FAR outside of our scope. 

Best wishes

**Comment by Clockwork-Muse** [comment]
@drizuid - Except the DHCP setup is something you [display prominently in the readme](https://github.com/linuxserver/docker-netbootxyz#openwrt).

As near as I'm aware your readme is the **only** documentation for netbootxyz DHCP setup.

**Comment by drizuid** [comment]
the netboot.xyz is where we got that info and we provide that static set as a courtesy.
