### ISSUE TITLE
Discord Server Expired Links?

### ISSUE THREAD

**Issue by brylor** [linuxserver/docker-netbootxyz#55]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Is the discord server still active? 

All the invite links I could find are expired.

Thank you

### Steps To Reproduce

Expired discord links:

https://discord.gg/An6PA2a posted here: https://netboot.xyz/docs/community/contributing
https://discord.gg/YWrKVTn when creating a new issue in github

### CPU architecture

x86-64

### Docker creation

```bash
na
```

### Container logs

```bash
na
```

**Comment by aptalca** [comment]
First link you posted is for a different project and dev team. We are not netboot.xyz
We are linuxserver.io and we provide a docker image for netboot.xyz among hundreds of others.

The second link is for our discord server and is active

**Comment by brylor** [comment]
OH so sorry! 

Well, for https://discord.gg/YWrKVTn I still get Invite Invalid.
