### ISSUE TITLE
[BUG] Could not boot: Permission denied

### ISSUE THREAD

**Issue by JohnyBeGood** [linuxserver/docker-netbootxyz#56]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

None of the "Live CDs" versions can't boot. I'm getting this https://prnt.sc/vpTn9Jl7yU2q
ie. When I select Ubuntu 21.04

### Expected Behavior

To be able to boot in any Live CD.

### Steps To Reproduce

Start by selecting any of the live CDs options.

### Environment

```markdown
- OS: Ubuntu 22.04
- How docker service was installed: On the host
```

### CPU architecture

x86-64

### Docker creation

```bash
Compose file:

---
version: "2.1"
services:
  netbootxyz:
    image: lscr.io/linuxserver/netbootxyz:latest
    container_name: netbootxyz
    environment:
      - PUID=1000 #current user
      - PGID=1000 #current group
    volumes:
      - /home/johnny/docker-stuff/netboot_xyz/config:/config # optional
      - /home/johnny/docker-stuff/netboot_xyz/assets:/assets # optional
    ports:
      - 3000:3000
      - 69:69/udp
      - 8080:80 #optional
    restart: unless-stopped
```

### Container logs

```bash
Container log but I'm not sure if its related to my issue: pastebin.com/TXGZBhVh
```

**Comment by Roxedus** [comment]
Please post the full container logs. 

Is this a rootless install?

**Comment by drizuid** [comment]
https://github.com/linuxserver/docker-netbootxyz/issues/56#issuecomment-1808836932
